# Generated by Django 2.1.1 on 2018-10-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retina',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
